/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jccam
 */
public class AnadirInv extends javax.swing.JFrame {

    int xMouse, yMouse;
    Connection connection;
    Statement statement = null;
    ResultSet resultSet = null;
    DefaultTableModel modelo, modeloL;
    Conexion con = new Conexion();
    int idc, fila = -1, list = 0, filaL = -1;
    float mont = 0, imp = 0;
    String title, aut, gen, tipo;
    String tituloL, genL, autL, tipoL, sql, precio;
    String tipoLibro, dibujante, tipoNovela;
    Float precioCompra;
    int numE, cod, numTV;
    
    /**
     * Creates new form AnadirInv
     */
    public AnadirInv() {
        initComponents();
        conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBooks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bookTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        autorTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipoTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        precioTF = new javax.swing.JTextField();
        btnAnadir = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        tipoCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        dibujanteTF = new javax.swing.JTextField();
        precioL = new javax.swing.JLabel();
        precioCTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        notomoTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        noejemTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Titulo"
            }
        ));
        tablaBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBooks);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 254, 458));

        jLabel1.setText("Titulo del libro:");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 106, -1, -1));

        bookTF.setForeground(java.awt.Color.gray);
        bookTF.setText("Ingrese titulo del libro");
        bookTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookTFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookTFMousePressed(evt);
            }
        });
        bg.add(bookTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 128, 143, -1));

        jLabel2.setText("Autor:");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 106, 42, -1));

        autorTF.setForeground(java.awt.Color.gray);
        autorTF.setText("Ingrese autor");
        autorTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                autorTFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                autorTFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                autorTFMousePressed(evt);
            }
        });
        bg.add(autorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 128, 146, -1));

        jLabel3.setText("Genero:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 178, -1, -1));

        tipoTF.setForeground(java.awt.Color.gray);
        tipoTF.setText("Ingrese genero");
        tipoTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tipoTFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tipoTFMousePressed(evt);
            }
        });
        bg.add(tipoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 212, 143, -1));

        jLabel4.setText("Precio Venta:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 178, 70, -1));

        precioTF.setForeground(java.awt.Color.gray);
        precioTF.setText("Ingrese precio");
        precioTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                precioTFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                precioTFMousePressed(evt);
            }
        });
        bg.add(precioTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 212, 146, -1));

        btnAnadir.setBackground(new java.awt.Color(228, 226, 226));
        btnAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnadirMouseExited(evt);
            }
        });

        jLabel5.setText("AÑADIR");

        javax.swing.GroupLayout btnAnadirLayout = new javax.swing.GroupLayout(btnAnadir);
        btnAnadir.setLayout(btnAnadirLayout);
        btnAnadirLayout.setHorizontalGroup(
            btnAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAnadirLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        btnAnadirLayout.setVerticalGroup(
            btnAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAnadirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        bg.add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        btnDelete.setBackground(new java.awt.Color(228, 226, 226));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        jLabel6.setText("ELIMINAR");

        javax.swing.GroupLayout btnDeleteLayout = new javax.swing.GroupLayout(btnDelete);
        btnDelete.setLayout(btnDeleteLayout);
        btnDeleteLayout.setHorizontalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDeleteLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );
        btnDeleteLayout.setVerticalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDeleteLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(21, 21, 21))
        );

        bg.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        btnSearch.setBackground(new java.awt.Color(228, 226, 226));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });

        jLabel7.setText("BUSCAR");

        javax.swing.GroupLayout btnSearchLayout = new javax.swing.GroupLayout(btnSearch);
        btnSearch.setLayout(btnSearchLayout);
        btnSearchLayout.setHorizontalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        btnSearchLayout.setVerticalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        bg.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(228, 226, 226));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseExited(evt);
            }
        });

        jLabel9.setText("LIMPIAR");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, 58));

        favicon.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        favicon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logopanini.png"))); // NOI18N
        bg.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 14, -1, -1));

        btnBack.setBackground(new java.awt.Color(228, 226, 226));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        jLabel10.setText("REGRESAR");

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, -1, -1));

        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        exitTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitTxt.setText("X");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitTxt)
                .addContainerGap())
        );

        bg.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 800, 50));

        tipoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manga", "Novela" }));
        bg.add(tipoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jLabel8.setText("Dibujante/tipo de novela:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, -1));

        dibujanteTF.setForeground(java.awt.Color.gray);
        dibujanteTF.setText("Ingrese dibujante/tipo");
        dibujanteTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dibujanteTFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dibujanteTFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dibujanteTFMousePressed(evt);
            }
        });
        bg.add(dibujanteTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, -1));

        precioL.setText("PrecioCompra:");
        bg.add(precioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        precioCTF.setForeground(java.awt.Color.gray);
        precioCTF.setText("Ingresa precio");
        precioCTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                precioCTFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                precioCTFMousePressed(evt);
            }
        });
        bg.add(precioCTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 120, -1));

        jLabel12.setText("Tipo:");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jLabel13.setText("No. de tomo/vol:");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        notomoTF.setForeground(java.awt.Color.gray);
        notomoTF.setText("Ingresa no.");
        notomoTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notomoTFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notomoTFMousePressed(evt);
            }
        });
        bg.add(notomoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel14.setText("No. de ejemplares:");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        noejemTF.setForeground(java.awt.Color.gray);
        noejemTF.setText("Ingresa no.");
        noejemTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noejemTFMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noejemTFMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                noejemTFMousePressed(evt);
            }
        });
        bg.add(noejemTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        //String tituloL, genL, autL, tipoL, sql;
        tituloL = bookTF.getText();
        genL = tipoTF.getText();
        autL = autorTF.getText();
        //tipoL = String.valueOf(cbTipo.getSelectedItem());
        if (tituloL.equals("Ingrese titulo del libro") && genL.equals("Ingrese genero") && autL.equals("Ingrese autor")) {
            JOptionPane.showMessageDialog(null, "Ingresa en un campo valido");
        } else if (genL.equals("Ingrese genero") && autL.equals("Ingrese autor")){
            modelo.setRowCount(0);
            sql = "SELECT titulo, numTom FROM mangas where titulo like '%" + tituloL + "%'";
            imprimirTabla(sql);
            if (modelo.getRowCount() == 0){
                sql = "SELECT titulo, numVol FROM novelas where titulo like '%" + tituloL + "%'";
            imprimirTabla2(sql);
            }
        } else if (tituloL.equals("Ingrese titulo del libro") && genL.equals("Ingrese genero")){
            modelo.setRowCount(0);
            sql = "SELECT titulo, numTom FROM mangas where autorManga like '%" + autL + "%'";
            imprimirTabla(sql);
            if (modelo.getRowCount() == 0){
                sql = "SELECT titulo, numVol FROM novelas where autor like '%" + autL + "%'";
            imprimirTabla2(sql);
            }
        } else if (tituloL.equals("Ingrese titulo del libro") && autL.equals("Ingrese autor")){
            modelo.setRowCount(0);
            sql = "SELECT titulo, numTom FROM mangas where genero like '%" + genL + "%'";
            imprimirTabla(sql);
            if (modelo.getRowCount() == 0){
                sql = "SELECT titulo, numVol FROM novelas where genero like '%" + genL + "%'";
            imprimirTabla2(sql);
            }
        } 
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        modelo.setRowCount(0);
        String sql = "SELECT titulo, numTom FROM mangas";
        imprimirTabla(sql);
        String consult = "SELECT titulo, numVol FROM novelas";
        imprimirTabla2(consult);
        tipoTF.setText("Ingrese genero");
        tipoTF.setForeground(Color.gray);
        bookTF.setText("Ingrese titulo del libro");
        bookTF.setForeground(Color.gray);
        autorTF.setText("Ingrese autor");
        autorTF.setForeground(Color.gray);
        precioTF.setText("Ingrese precio");
        precioTF.setForeground(Color.gray);
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseClicked
        // TODO add your handling code here:
        tituloL = bookTF.getText();
        genL = tipoTF.getText();
        autL = autorTF.getText();
        precio = precioTF.getText();
        dibujante = dibujanteTF.getText();
        precioCompra = Float.valueOf(precioCTF.getText());
        numE =Integer.parseInt(noejemTF.getText());
        numTV = Integer.parseInt(notomoTF.getText());
        if (tituloL.equals("Ingrese titulo del libro") || genL.equals("Ingrese genero") || autL.equals("Ingrese autor") || precio.equals("Ingrese precio")) {
            JOptionPane.showMessageDialog(null, "Llena todos los campos");
        } else if (tipoCB.getSelectedIndex() == 0){
            sql = "Insert into mangas (titulo, genero, autorManga, precioCompra, precioVenta, numTom, dibujante, numEjemplares) values "
                    + "('" + tituloL + "', '" + genL +"', '" + autL + "', " +  precioCompra + ", " + precio + ", " +  numTV + ", '" + dibujante + "', " + numE + ");";
            System.out.println(sql);
            ejecutarQuery(sql);
        } else {
            sql = "Insert into novelas (titulo, genero, autor, precioCompra, precioVenta, tipoNovela, numVol, numEjemplares) values "
                    + "('" + tituloL + "', '" + genL +"', '" + autL + "', " +  precioCompra + ", " + precio + ", '" + dibujante + "', " +  numTV + ", "  + numE + ");";
            System.out.println(sql);
            ejecutarQuery(sql);
        }
    }//GEN-LAST:event_btnAnadirMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        tituloL = bookTF.getText();
        if (tipoCB.getSelectedIndex() == 0){
            sql = "Delete from mangas where titulo like '%" + tituloL + "%'";
        } else {
            sql = "Delete from novelas where titulo like '%" + tituloL + "%'";
        }
        
        System.out.println(sql);
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if(respuesta == JOptionPane.YES_OPTION){
            System.out.println("Si");
            ejecutarQuery(sql);
        } else if (respuesta == JOptionPane.NO_OPTION){
            System.out.println("No");
        } else {
            System.out.println("No esta seguro");
        }
        //ejecutarQuery(sql);
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        MenuGeneral menu = new MenuGeneral();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void bookTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTFMousePressed
        // TODO add your handling code here:
        if (bookTF.getText().equals("Ingrese titulo del libro")) {
            bookTF.setText("");
            bookTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_bookTFMousePressed

    private void bookTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTFMouseExited
        // TODO add your handling code here:
        if (bookTF.getText().equals("")) {
            bookTF.setText("Ingrese titulo del libro");
            bookTF.setForeground(Color.gray);
        }
    }//GEN-LAST:event_bookTFMouseExited

    private void autorTFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autorTFMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_autorTFMouseEntered

    private void autorTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autorTFMouseExited
        // TODO add your handling code here:
        if (autorTF.getText().equals("")) {
            autorTF.setText("Ingrese autor");
            autorTF.setForeground(Color.gray);
        }
    }//GEN-LAST:event_autorTFMouseExited

    private void autorTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autorTFMousePressed
        // TODO add your handling code here:
        if (autorTF.getText().equals("Ingrese autor")) {
            autorTF.setText("");
            autorTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_autorTFMousePressed

    private void tipoTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoTFMousePressed
        // TODO add your handling code here:
        if (tipoTF.getText().equals("Ingrese genero")) {
            tipoTF.setText("");
            tipoTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_tipoTFMousePressed

    private void tipoTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoTFMouseExited
        // TODO add your handling code here:
        if (tipoTF.getText().equals("")) {
            tipoTF.setText("Ingrese genero");
            tipoTF.setForeground(Color.gray);
        }
    }//GEN-LAST:event_tipoTFMouseExited

    private void precioTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioTFMousePressed
        // TODO add your handling code here:
        if (precioTF.getText().equals("Ingrese precio")) {
            precioTF.setText("");
            precioTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_precioTFMousePressed

    private void precioTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioTFMouseExited
        // TODO add your handling code here:
        if (precioTF.getText().equals("")) {
            precioTF.setText("Ingrese precio");
            precioTF.setForeground(Color.gray);
        }
    }//GEN-LAST:event_precioTFMouseExited

    private void tablaBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBooksMouseClicked
        // TODO add your handling code here:
        cod = 0;
        int found = 0;
        fila = tablaBooks.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "No se selecciono ningun libro");
        } else{
            try {
                idc = Integer.parseInt((String) tablaBooks.getValueAt(fila, 0).toString()); 
                String tituloL =  tablaBooks.getValueAt(fila, 1).toString();
                statement = connection.createStatement();
                String sql = "SELECT * FROM mangas";
                resultSet = statement.executeQuery(sql);
                while(resultSet.next()){
                    cod = resultSet.getInt("numTom");
                    title = resultSet.getString("titulo");
                    aut = resultSet.getString("autorManga");
                    gen = resultSet.getString("genero");
                    mont = resultSet.getFloat("precioVenta");
                    precioCompra = resultSet.getFloat("precioCompra");
                    dibujante = resultSet.getString("dibujante");
                    numE = resultSet.getInt("numEjemplares");
                    if(idc == cod){
                        bookTF.setForeground(Color.black);
                        bookTF.setText(title);
                        autorTF.setText(aut);
                        tipoTF.setText(gen);
                        precioTF.setText(String.valueOf(mont));
                        precioCTF.setText(String.valueOf(precioCompra));
                        dibujanteTF.setText(dibujante);
                        notomoTF.setText(String.valueOf(cod));
                        noejemTF.setText(String.valueOf(numE));
                        tipoCB.setSelectedIndex(0);
                        found = 1;
                        tipoLibro = "Manga";
                        break;
                    }
                }
                if (found == 0) {
                    String sql2 = "SELECT * FROM novelas";
                    resultSet = statement.executeQuery(sql2);
                    while (resultSet.next()) {
                        cod = resultSet.getInt("numVol");
                        title = resultSet.getString("titulo");
                        aut = resultSet.getString("autor");
                        gen = resultSet.getString("genero");
                        mont = resultSet.getFloat("precioVenta");
                        precioCompra = resultSet.getFloat("precioCompra");
                        tipoNovela = resultSet.getString("tipoNovela");
                        numE = resultSet.getInt("numEjemplares");
                        //tipo = resultSet.getString("tipo_Lib");
                        if (tituloL.equals(title)) {
                            bookTF.setForeground(Color.black);
                            bookTF.setText(title);
                            autorTF.setText(aut);
                            tipoTF.setText(gen);
                            precioTF.setText(String.valueOf(mont));
                            precioCTF.setText(String.valueOf(precioCompra));
                            dibujanteTF.setText(tipoNovela);
                            notomoTF.setText(String.valueOf(cod));
                            noejemTF.setText(String.valueOf(numE));
                            tipoCB.setSelectedIndex(1);
                            tipoLibro = "Novela";
                            break;
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tablaBooksMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        // TODO add your handling code here:
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        // TODO add your handling code here:
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitBtnMouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
        btnSearch.setBackground(new Color(235, 232, 24));
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // TODO add your handling code here:
        btnSearch.setBackground(new Color(242, 242, 242)); 
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseEntered
        // TODO add your handling code here:
        btnLimpiar.setBackground(new Color(235, 232, 24));
    }//GEN-LAST:event_btnLimpiarMouseEntered

    private void btnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseExited
        // TODO add your handling code here:
        btnLimpiar.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnLimpiarMouseExited

    private void btnAnadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseEntered
        // TODO add your handling code here:
        btnAnadir.setBackground(new Color(235, 232, 24));
    }//GEN-LAST:event_btnAnadirMouseEntered

    private void btnAnadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirMouseExited
        // TODO add your handling code here:
        btnAnadir.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnAnadirMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        // TODO add your handling code here:
        btnDelete.setBackground(new Color(235, 232, 24));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        // TODO add your handling code here:
        btnDelete.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(new Color(235, 232, 24));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnBackMouseExited

    private void dibujanteTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dibujanteTFMouseExited
        // TODO add your handling code here:
        if (dibujanteTF.getText().equals("")) {
            dibujanteTF.setText("Ingrese dibujante/tipo");
            dibujanteTF.setForeground(Color.gray);
        }
    }//GEN-LAST:event_dibujanteTFMouseExited

    private void dibujanteTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dibujanteTFMousePressed
        // TODO add your handling code here:
        if (dibujanteTF.getText().equals("Ingrese dibujante/tipo")) {
            dibujanteTF.setText("");
            dibujanteTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_dibujanteTFMousePressed

    private void dibujanteTFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dibujanteTFMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dibujanteTFMouseEntered

    private void precioCTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioCTFMousePressed
        // TODO add your handling code here:
        if (precioCTF.getText().equals("Ingresa precio")) {
            precioCTF.setText("");
            precioCTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_precioCTFMousePressed

    private void precioCTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioCTFMouseExited
        // TODO add your handling code here:
        if (precioCTF.getText().equals("")) {
            precioCTF.setText("Ingresa precio");
            precioCTF.setForeground(Color.gray);
        }
    }//GEN-LAST:event_precioCTFMouseExited

    private void notomoTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notomoTFMousePressed
        // TODO add your handling code here:
        if (notomoTF.getText().equals("Ingresa no.")) {
            notomoTF.setText("");
            notomoTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_notomoTFMousePressed

    private void notomoTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notomoTFMouseExited
        // TODO add your handling code here:
        if (notomoTF.getText().equals("")) {
            notomoTF.setText("Ingresa no.");
            notomoTF.setForeground(Color.gray);
        }
    }//GEN-LAST:event_notomoTFMouseExited

    private void noejemTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noejemTFMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_noejemTFMouseClicked

    private void noejemTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noejemTFMousePressed
        // TODO add your handling code here:
        if (noejemTF.getText().equals("Ingresa no.")) {
            noejemTF.setText("");
            noejemTF.setForeground(Color.black);
        }
    }//GEN-LAST:event_noejemTFMousePressed

    private void noejemTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noejemTFMouseExited
        // TODO add your handling code here:
        if (noejemTF.getText().equals("")) {
            noejemTF.setText("Ingresa no.");
            noejemTF.setForeground(Color.gray);
        }
    }//GEN-LAST:event_noejemTFMouseExited

    public void conectar() {
        connection = con.getCon();
        String sql = "SELECT titulo, numTom FROM mangas";
        imprimirTabla(sql);
        String consult = "SELECT titulo, numVol FROM novelas";
        imprimirTabla2(consult);
    }

    public void imprimirTabla(String sql) {
        try {
            statement = connection.createStatement();
            //String sql = "SELECT codLibro, nom_Lib FROM Libros";
            resultSet = statement.executeQuery(sql);
            Object[] libro = new Object[2];
            modelo = (DefaultTableModel) tablaBooks.getModel();
            while(resultSet.next()){
                libro[0] = resultSet.getInt("numTom");
                libro[1] = resultSet.getString("titulo");
                modelo.addRow(libro);
            }
            tablaBooks.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void imprimirTabla2(String sql){
        try {
            statement = connection.createStatement();
            //String sql = "SELECT codLibro, nom_Lib FROM Libros";
            resultSet = statement.executeQuery(sql);
            Object[] libro = new Object[2];
            modelo = (DefaultTableModel) tablaBooks.getModel();
            while(resultSet.next()){
                libro[0] = resultSet.getInt("numVol");
                libro[1] = resultSet.getString("titulo");
                modelo.addRow(libro);
            }
            tablaBooks.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void ejecutarQuery(String consulta){
        try {
            statement = connection.createStatement();
            //String sql = "SELECT codLibro, nom_Lib FROM Libros";
            //resultSet = statement.executeQuery(consulta);
            statement.executeUpdate(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(AnadirInv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnadirInv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autorTF;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField bookTF;
    private javax.swing.JPanel btnAnadir;
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnDelete;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnSearch;
    private javax.swing.JTextField dibujanteTF;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel favicon;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noejemTF;
    private javax.swing.JTextField notomoTF;
    private javax.swing.JTextField precioCTF;
    private javax.swing.JLabel precioL;
    private javax.swing.JTextField precioTF;
    private javax.swing.JTable tablaBooks;
    private javax.swing.JComboBox<String> tipoCB;
    private javax.swing.JTextField tipoTF;
    // End of variables declaration//GEN-END:variables
}
