/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jccam
 */
public class AnadirPed extends javax.swing.JFrame {

    int xMouse, yMouse;
    Connection connection;
    Statement statement = null;
    ResultSet resultSet = null;
    DefaultTableModel modelo, modeloL;
    Conexion con = new Conexion();
    int idc, fila = -1, list = 0, filaL = -1;
    float mont = 0, imp = 0;
    String title, aut, gen, tipo;
    String tituloL, genL, autL, tipoL, sql, precio, fecha;
    String tipoLibro, dibujante, tipoNovela;
    Float precioCompra;
    int numE, cod, numTV, cant, prov;
     LocalDate fechaActual = LocalDate.now(); // Solo la fecha
        LocalTime horaActual = LocalTime.now(); // Solo la hora

        // Formatea la fecha y hora (opcional)
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm:ss");
        String fechaFormateada = fechaActual.format(formatoFecha);
        String horaFormateada = horaActual.format(formatoHora);
    
    /**
     * Creates new form AnadirPed
     */
    public AnadirPed() {
        initComponents();
        conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBooks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tipoCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tituloTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cantTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        proveedorTF = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Fecha pedido"
            }
        ));
        tablaBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBooks);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 107, 270, 360));

        jLabel1.setText("Tipo de libro");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        tipoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manga", "Novela" }));
        bg.add(tipoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel2.setText("Titulo:");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        tituloTF.setText("Ingrese el titulo");
        bg.add(tituloTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jLabel3.setText("Cant. a pedir:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jLabel5.setText("BUSCAR");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(30, 30, 30))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );

        bg.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, 50));

        cantTF.setText("0");
        bg.add(cantTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 80, -1));

        jLabel4.setText("Proveedor");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        proveedorTF.setText("0");
        bg.add(proveedorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 80, -1));

        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        jLabel6.setText("LIMPIAR");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLimpiarLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(29, 29, 29))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLimpiarLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(16, 16, 16))
        );

        bg.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 100, 50));

        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAñadirMouseClicked(evt);
            }
        });

        jLabel7.setText("AÑADIR");

        javax.swing.GroupLayout btnAñadirLayout = new javax.swing.GroupLayout(btnAñadir);
        btnAñadir.setLayout(btnAñadirLayout);
        btnAñadirLayout.setHorizontalGroup(
            btnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAñadirLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        btnAñadirLayout.setVerticalGroup(
            btnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAñadirLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bg.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 110, 60));

        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        jLabel8.setText("ELIMINAR");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(20, 20, 20))
        );

        bg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 100, 60));

        favicon.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        favicon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logopanini.png"))); // NOI18N
        bg.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 280, 90));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel9.setText("REGRESAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        int tipoL = tipoCB.getSelectedIndex();
        tituloL = tituloTF.getText();
        //genL = tipoTF.getText();
        cant = Integer.parseInt(cantTF.getText());
        //autL = proveedorTF.getText();
        prov = Integer.parseInt(proveedorTF.getText());
        //tipoL = String.valueOf(cbTipo.getSelectedItem());
        if (tituloL.equals("Ingrese el titulo") && cant == 0 && prov == 0) {
            JOptionPane.showMessageDialog(null, "Ingresa en un campo valido");
        } else if (cant == 0 && prov == 0){
            modelo.setRowCount(0);
            sql = "SELECT titulo, fechaPedido FROM pedido where titulo like '%" + tituloL + "%'";
            imprimirTabla(sql);
        } else if (tituloL.equals("Ingrese el titulo") && cant == 0){
            modelo.setRowCount(0);
            sql = "SELECT titulo, fechaPedido FROM pedido where proveedor = " + prov;
            imprimirTabla(sql);
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseClicked
        // TODO add your handling code here:
        int tipoL = tipoCB.getSelectedIndex();
        tituloL = tituloTF.getText();
        //genL = tipoTF.getText();
        cant = Integer.parseInt(cantTF.getText());
        //autL = proveedorTF.getText();
        prov = Integer.parseInt(proveedorTF.getText());
        if (tituloL.equals("Ingrese el titulo") && cant == 0 && prov == 0) {
            JOptionPane.showMessageDialog(null, "Llena todos los campos");
        } else if (tipoL == 0){
            sql = "insert into pedido (tipoLibro, titulo, cantPedir, proveedor, fechaPedido) values "
                    + "('Manga', '" + tituloL + "', " + cant + ", " + prov + ", '" + fechaFormateada + "');";
            System.out.println(sql);
            ejecutarQuery(sql);
        } else {
            sql = "insert into pedido (tipoLibro, titulo, cantPedir, proveedor, fechaPedido) values "
                    + "('Novela', '" + tituloL + "', " + cant + ", " + prov + ", '" + fechaFormateada + "');";
            System.out.println(sql);
            ejecutarQuery(sql);
        }
    }//GEN-LAST:event_btnAñadirMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        modelo.setRowCount(0);
        String sql = "SELECT titulo, fechaPedido FROM pedido";
        imprimirTabla(sql);
        tituloTF.setText("Ingrese el titulo");
        tituloTF.setForeground(Color.GRAY);
        cantTF.setText("0");
        cantTF.setForeground(Color.GRAY);
        proveedorTF.setText("0");
        proveedorTF.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        tituloL = tituloTF.getText();
        sql = "Delete from pedido where titulo like '%" + tituloL + "%'";
        System.out.println(sql);
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if(respuesta == JOptionPane.YES_OPTION){
            System.out.println("Si");
            ejecutarQuery(sql);
        } else if (respuesta == JOptionPane.NO_OPTION){
            System.out.println("No");
        } else {
            System.out.println("No esta seguro");
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void tablaBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBooksMouseClicked
        // TODO add your handling code here:
        cod = 0;
        int found = 0;
        fila = tablaBooks.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "No se selecciono ningun libro");
        } else{
            try {
                //idc = Integer.parseInt((String) tablaBooks.getValueAt(fila, 0).toString()); 
                String tituloL =  tablaBooks.getValueAt(fila, 0).toString();
                System.out.println(tituloL);
                statement = connection.createStatement();
                String sql = "SELECT * FROM pedido";
                resultSet = statement.executeQuery(sql);
                while (resultSet.next()) {
                    tipoL = resultSet.getString("tipoLibro");
                    title = resultSet.getString("titulo");
                    cant = resultSet.getInt("cantPedir");
                    prov = resultSet.getInt("proveedor");
                    fecha = resultSet.getString("fechaPedido");
                    System.out.println(title);
                    if (tituloL.equals(title)) {
                        tituloTF.setText(title);
                        cantTF.setText(String.valueOf(cant));
                        proveedorTF.setText(String.valueOf(prov));
                        if (tipoL.equals("Manga")) {
                            tipoCB.setSelectedIndex(0);
                        } else {
                            tipoCB.setSelectedIndex(1);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tablaBooksMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        MenuGeneral menu = new MenuGeneral();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    public void conectar() {
        connection = con.getCon();
        String sql = "SELECT titulo, fechaPedido FROM pedido";
        imprimirTabla(sql);
    }

    public void imprimirTabla(String sql) {
        try {
            statement = connection.createStatement();
            //String sql = "SELECT codLibro, nom_Lib FROM Libros";
            resultSet = statement.executeQuery(sql);
            Object[] libro = new Object[2];
            modelo = (DefaultTableModel) tablaBooks.getModel();
            while(resultSet.next()){
                libro[0] = resultSet.getString("titulo");
                libro[1] = resultSet.getString("fechaPedido");
                modelo.addRow(libro);
            }
            tablaBooks.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(MenuLibros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void ejecutarQuery(String consulta){
        try {
            statement = connection.createStatement();
            //String sql = "SELECT codLibro, nom_Lib FROM Libros";
            //resultSet = statement.executeQuery(consulta);
            statement.executeUpdate(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(AnadirInv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnadirPed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnAñadir;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JTextField cantTF;
    private javax.swing.JLabel favicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField proveedorTF;
    private javax.swing.JTable tablaBooks;
    private javax.swing.JComboBox<String> tipoCB;
    private javax.swing.JTextField tituloTF;
    // End of variables declaration//GEN-END:variables
}
